# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NanoGirls' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NanoGirls
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'NanoGirlsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
  end

  target 'NanoGirlsUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database' 
  end

end
